--- #################### 注册中心相关配置 ####################

spring:
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        namespace: public # 命名空间。这里使用 dev 开发环境
server:
  port: 8080
--- #################### 配置中心相关配置 ####################

spring:
  cloud:
    nacos:
      # Nacos Config 配置项，对应 NacosConfigProperties 配置属性类
      config:
        server-addr: http://localhost:8848 # Nacos 服务器地址
        namespace: public # 命名空间。这里使用 dev 开发环境
        group:  # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        name: # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
        file-extension: yaml # 使用的 Nacos 配置集的 dataId 的文件拓展名，同时也是 Nacos 配置集的配置格式，默认为 properties
  r2dbc:
    url: r2dbc:mysql://localhost:3306/data-center?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    name: data-center

